- client/src/components/Slack/Slack.js
Update Add to Slack button Client Id from old slack api account to new slack api account
> update add to slack button client id

- client/src/components/Dashboard/Dashboard.js
- client/src/components/Onboarding/CreateTeam.js
- client/src/components/Onboarding/JoinTeam.js
- client/src/components/Onboarding/LandingPage.js
- client/src/components/Onboarding/Onboarding.js
- client/src/components/Onboarding/onboarding.css
We have decided to remove the need for members to have a join code. Managers will now only be able to add people from their view in the app. Removing the need for a regular team member to need to sign into our app. Making this purely a management tool,
> Join code purge

- client/src/components/Dashboard/Dashboard.js
- client/src/components/Profile/Profile.js
deleted the join code from the profile 
work as expected)
> deleted join profile and comments talking about join code

- client/src/components/Onboarding/CreateTeam.js
removed join existing team in team data
> removed join existing team in onbording

- client/src/components/Dashboard/ReportsDash.js
- client/src/components/Reports/MemberReports/MemberResponseForm.js
- client/src/components/Reports/MemberReports/SentimentInput.js
- client/src/components/Reports/ModifyReports/ChooseReport.js
- client/src/components/Reports/ModifyReports/CreateReport.js
- client/src/components/Reports/ModifyReports/CreateSentiment.js
- client/src/components/Reports/Reports.js
Adding the ability to have sentiment report responses and polls separate from regular polls, added the isSentiment boolean variable to the create a report. 
> Erica chen

- client/src/components/Onboarding/Onboarding.js
> set roles to admin instead of member when user clicks create team

- client/src/components/Reports/ModifyReports/CreatePoll.js
- client/src/components/Reports/ModifyReports/CreateReport.js
my changes are for the beginning of a drop down menu that will hold the questions for the manager questions and stand-up questions
> Curtis hubbard

- client/package.json
> Fixed breaking bug

- client/src/components/Reports/ModifyReports/CreateReport.js
Finished touching up the survey questions.
> Survey report

- client/src/components/Navigation/Navigations.js
- client/src/components/Reports/ModifyReports/CreateReport.js
Linked nav, some minior changes, and removed 2 useless functions in createReport
> Linked nav and changed some CSS 

- client/src/components/Reports/MemberReports/MemberResponseForm.js
- client/src/components/Reports/MemberReports/ReportInput.js
- client/src/components/Reports/MemberReports/ReportResults.js
Added in functionality of being able to handle multiple sentiment responses within one sentiment survey and sending that to the backend.
- [x ] Complete, tested, ready to review and merge
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
> Feature sentiment reports

- client/package.json
- client/src/components/Reports/MemberReports/MemberResponseForm.js
- client/src/components/Reports/MemberReports/ReportInput.js
- client/src/components/Reports/MemberReports/ReportResults.js
- client/yarn.lock
SentimentRange and answers are both sending to the BE to save into the DB now. However, the code feels janky. Please 
> Ben tsao dev

- client/src/components/Reports/MemberReports/MemberResponseForm.js
> fixed setement error

- client/package.json
- client/public/index.html
- client/src/components/InviteUser.js
- client/src/components/PollCalendar.js
- client/src/components/SummaryBox.css
- client/src/components/TableDisplay.js
- client/src/components/circleProgress.css
- client/src/components/circleProgress.js
- client/src/components/pagetitle.css
- client/src/components/pollCalendar.css
- client/src/components/tableDisplay.css
- client/src/pages/Dashboard/Dashboard.js
- client/src/pages/Dashboard/dashboard.css
- client/src/pages/Navigation/Navigations.js
- client/src/pages/Reports/MemberReports/ReportResults.css
- client/src/pages/Reports/reports.css
- client/src/pages/Stats/StatsDashboard.js
- client/src/pages/Stats/pollCalendar.css
- client/src/pages/View/View.js
- client/src/pages/View/view.css
- client/yarn.lock
Edited the circle progress and dashboard reports component
> Circle progress and reports component 

- client/src/auth/PrivateRoute.js
- client/src/pages/Firebase/Firebase.js
- client/src/pages/Navigation/Navigations.js
- client/src/pages/Profile/Profile.js
- client/src/pages/Reports/MemberReports/MemberResponseForm.js
- client/src/pages/Reports/MemberReports/ReportInput.js
- client/src/pages/Reports/MemberReports/ReportResults.js
- client/src/pages/Reports/ModifyReports/ChooseReport.js
- client/src/pages/Reports/ModifyReports/CreateReport.js
- client/src/pages/Reports/ModifyReports/CreateSentiment.js
- client/src/pages/Reports/ModifyReports/EditReport.js
- client/src/pages/Slack/SlackRedirect.js
Fix the issue where the FE is not sending the manager questions to the BE
> Feature manager questions

- client/src/components/Reports/TemplateMaker.js
- client/src/pages/Onboarding/CreateTeam.js
- client/src/pages/Reports/MemberReports/ReportInput.js
- client/src/pages/Reports/MemberReports/Report_Input.css
> removed comment button fron stand up response forms

- client/src/App.js
- client/src/components/PageDescription.js
- client/src/components/TableDisplay.js
- client/src/components/pagetitle.css
- client/src/pages/Dashboard/Dashboard.js
- client/src/pages/MyTeam/myTeam.js
- client/src/pages/Navigation/Navigations.js
- client/src/pages/Navigation/navigation.css
- client/src/pages/Profile/Profile.js
- client/src/pages/Reports/MemberReports/ReportResults.css
- client/src/pages/Reports/MemberReports/ReportResults.js
- client/src/pages/Reports/ModifyReports/Report.css
- client/src/pages/Reports/Reports.js
- client/src/pages/Stats/StatsDashboard.js
- client/src/pages/View/View.js
- client/src/pages/View/view.css
Implemented changes to the responses table for new polls, still need to revamp the ui for responding to poll and calendar components. Also added some standardized ui components to the stats page. 
> Ui components

- client/src/components/circleProgress.js
- client/src/pages/Stats/SentimentChart.js
- client/src/pages/Stats/StatsDashboard.js
- client/src/pages/Stats/TodayPoll.js
Restyles the stats page to make it match the app.
No bugs.
> Restyles the Stats page.

- client/src/pages/Navigation/Navigations.js
- client/src/pages/Stats/SentimentChart.js
- client/src/pages/Stats/StatsDashboard.js
- client/src/pages/Stats/TodayPoll.js
Hides nav items for users not on a team.
Works as intended without additional bugs.
> Hides nav items for users not on a team.

- client/src/pages/Reports/MemberReports/ReportResults.js
- client/src/pages/View/View.js
Display submission rate in both report page and report dashboard page are both working. 
> Refactor default props

- client/package.json
- client/public/index.html
- client/src/pages/Dashboard/Dashboard.js
- client/src/pages/Dashboard/dashboard.css
- client/src/pages/Onboarding/LandingPage.js
- client/src/pages/View/View.js
- client/src/pages/View/view.css
- client/yarn.lock
created a breif tour of the reports page to inform users of it's features. Maybe I should add one to the stats page and one for each report type.
> Reports Walkthough

- client/src/pages/Reports/MemberReports/MemberResponseForm.js
- client/src/pages/Reports/MemberReports/ReportResults.css
- client/src/pages/Reports/MemberReports/ReportResults.js
- client/src/pages/Reports/ModifyReports/CreateReport.js
- client/src/pages/Responders/Responders.js
fixed bug with manager questions showing up in every report response form and also implemented a FE check to make sure all manager questions are filled in when toggled before user can submit the report 
- [x ] My code has been reviewed by at least one peer
- [x ] I have commented my code, particularly in hard-to-understand areas
> fixed bug with manager questions showing up in every report response form 

- client/src/pages/Reports/MemberReports/MemberResponseForm.js
- client/src/pages/Reports/ModifyReports/CreateReport.js
- client/src/pages/Reports/ModifyReports/Report.css
…ed in in create a new survey
Added styling in the create report app to make empty mandatory fields go red when not filled in to indicate to user which fields are required. Also pushing a bug fix that was preventing manager responses from being seen in the dashboard. 
- [ x] I have commented my code, particularly in hard-to-understand areas
- …
> added styling for empty mandatory fields in create report 

- client/src/pages/MyTeam/myTeam.js
pull request has mckays changes and my current changes to myTeam. This is not a major pull request but is to update master
> Change my team

- client/src/components/circleProgress.js
- client/src/pages/Dashboard/Dashboard.js
- client/src/pages/Reports/MemberReports/ReportResults.js
Pulled total poll responses into the home dashboard page and bug fix for duplicated responses in report results 
- [ x] There are no merge conflicts
> bug fix for duplicated responses and pulling in data

- client/src/components/tableDisplay.css
- client/src/pages/Reports/ModifyReports/CreateReport.js
- client/src/pages/Reports/ModifyReports/Report.css
Changes the UI for selecting days in reports for better User Testing.
Simple styling change.
> World's Smallest PR

- client/src/pages/Reports/ModifyReports/CreateReport.js
fixing bug that clears text field within the manager response within Standup survey
> fix bug with clearing text field

- client/public/index.html
- client/src/pages/Dashboard/Dashboard.js
- client/src/pages/Dashboard/dashboard.css
- client/src/pages/View/View.js
- client/yarn.lock
> user can now opt back into tour

- client/src/components/TableDisplay.js
- client/src/components/UserCard.js
- client/src/pages/Dashboard/Dashboard.js
- client/src/pages/Navigation/Navigations.js
- client/src/pages/Reports/MemberReports/MemberResponseForm.js
Added in some checks for roles throughout the app to adjust what's being displayed according to your role. Also combined sentiment and regular surveys so the user can only create one type of poll now 
> Admin v member ui interface changes + combining sentiment and surveys 

- client/src/components/ManagerPoll.js
- client/src/components/PollCalendar.js
- client/src/pages/Reports/MemberReports/MemberResponseForm.js
- client/src/pages/Reports/MemberReports/ReportInput.js
- client/src/pages/Reports/MemberReports/ReportResults.css
- client/src/pages/Reports/MemberReports/ReportResults.js
- client/src/pages/Reports/MemberReports/Report_Input.css
- client/src/pages/Reports/ModifyReports/CreateReport.js
Styled the calendar component and comments functionality for sentiment reports, can submit reports again--only regular answers for reports. Added in checks for roles so now managers can no longer answer their own reports--they can only answer manager polls. You have to add a team member and login as them to test report submission. 
- [x ] I have commented my code, particularly in hard-to-understand …
> Checks for roles, styled calendar component

- client/src/pages/Reports/MemberReports/MemberResponseForm.js
- client/src/pages/Reports/MemberReports/ReportResults.js
fixed some merge conflicts + errors with displaying the manager 
> fixed bug with merge conflicts

- client/src/components/ManagerPoll.js
- client/src/pages/Reports/MemberReports/ReportResults.js
> Fixed bug with reload() not being defined

- client/src/components/ManagerPoll.js
axios call for manager survey was commented out 
> uncommented axios call for creating a new manager survey

- client/src/components/TableDisplay.js
- client/src/components/tableDisplay.css
- client/src/pages/Reports/MemberReports/MemberResponseForm.js
- client/src/pages/Reports/MemberReports/ReportResults.js
- client/src/pages/Reports/ModifyReports/CreateReport.js
Adding Response button to each report to make it easier for users to navigate where to respond	
> Adding Response button to each survey. Changes to state

- client/src/pages/Reports/ModifyReports/CreateReport.js
- client/src/pages/View/View.js
I have reworded several things on the reports page, which are detailed in the commit messages.
I hope this new language will better help the users create better sentiment questions
> Re wording update

- client/src/pages/Stats/ChartOptions.js
- client/src/pages/Stats/StatsDashboard.js
User has the ability to select what kind of graph they would like to see. Currently you can select the timeframe and type of data you want to see. 
NOTE: Still working on displaying the right data depending on the selections. Next task.
Two Bugs:
1. Not really a bug, but you can't see the relevant data yet. Going to work on this next.
2. Bug where you have to refresh the page in order to select new options. Bug added to Trello.
> Renders graph with dates and data type.

- client/src/components/TableDisplay.js
- client/src/pages/Dashboard/ReportsDash.js
- client/src/pages/MyTeam/myTeam.js
- client/src/pages/Reports/MemberReports/MemberResponseForm.js
- client/src/pages/Reports/MemberReports/ReportResults.css
- client/src/pages/Reports/MemberReports/ReportResults.js
- client/src/pages/Reports/Reports.js
Reverts labs-13-slack-manager-survey/frontend#91
> Revert "Bug fixes and manager poll feature "

- client/src/pages/Reports/MemberReports/MemberResponseForm.js
- client/src/pages/Reports/MemberReports/ReportInput.js
Fixed a bug where reports aren't submitted to the backend correctly
> Feature manager questions flow

- client/src/pages/Onboarding/JoinTeam.js
- client/src/pages/Onboarding/Onboarding.js
- client/src/pages/Reports/SingleReport.js
- client/src/pages/View/View.js
removed the ability to create teams with invites now you have to add people via my teams page
> Removed create team page not the lnading page after log in is the only thing they will see

- client/src/pages/Reports/MemberReports/ReportResults.css
- client/src/pages/Reports/MemberReports/ReportResults.js
styled manager comments so that they show up in the list of responses differently; added a new function to filter the list and return one with manager responses at the top of each day--> not yet live. Got rid of bug that had user polls displaying twice and added various checks to debug inconsistencies in the manager and user views in regards to manager polls showing up. 
- [x ] I have performed a …
> Manager Poll debug 

- client/src/App.css
- client/src/pages/Reports/MemberReports/ReportResults.css
- client/src/pages/Reports/MemberReports/ReportResults.js
Now all reports are listed together with the manager polls on top. Also restyled the report list a bit; had to rewrite the component in order to get it to display in the new format. 
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] My changes generate no new warnings
> Built out the display view to display manager responses and user responses together by day

- client/src/App.css
- client/src/pages/Navigation/Navigations.js
- client/src/pages/Navigation/navigation.css
Add mobile responsiveness for the Nav bar
> Mobile nav

- client/src/pages/Reports/MemberReports/ReportResults.css
- client/src/pages/Reports/MemberReports/ReportResults.js
Bug fix to manager polls 
- [ x] Bug fix (non-breaking change which fixes an issue)
> bug fixes to manager polls

- client/src/pages/Stats/ChartOptions.js
- client/src/pages/Stats/SentimentChart.js
- client/src/pages/Stats/StatsDashboard.js
Pre-bug graphs.
Only known issues.
> generates reesponse rates by data and sentiment average by reports

- client/src/pages/Reports/ModifyReports/CreateReport.js
- client/src/pages/Reports/ModifyReports/EditReport.js
within each form I had to wrap the input field in a form tag to fix the issue and also add an onSubmit handler
- [] Complete, but not tested (may need new tests)
- [] My code follows the style guidelines of this project
> Add question with enter key fix

- client/src/pages/Stats/ChartOptions.js
- client/src/pages/Stats/StatsDashboard.css
- client/src/pages/Stats/StatsDashboard.js
Fixes the bugs on the stats page.
Tested all the bugs and they are now fixed without adding any extra bugs.
> fixes stats bugs

- client/src/components/SummaryBox.css
- client/src/components/TableDisplay.js
- client/src/components/TableHeader.js
- client/src/components/circleProgress.css
- client/src/components/pagetitle.css
- client/src/components/tableDisplay.css
- client/src/pages/Dashboard/Dashboard.js
- client/src/pages/Dashboard/dashboard.css
- client/src/pages/Navigation/navigation.css
- client/src/pages/Profile/Profile.js
- client/src/pages/Profile/profile.css
- client/src/pages/Reports/MemberReports/ReportResults.css
- client/src/pages/Reports/MemberReports/ReportResults.js
- client/src/pages/Reports/ModifyReports/CreateReport.js
- client/src/pages/Reports/ModifyReports/CreateSentiment.js
- client/src/pages/Reports/reports.css
- client/src/pages/Stats/StatsDashboard.js
- client/src/pages/View/view.css
Added in media queries for mobile view @ max-width 500px 
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
> Mobile view 

- client/src/pages/Reports/ModifyReports/CreateReport.js
- client/src/pages/Reports/ModifyReports/EditReport.js
- client/src/pages/Reports/ModifyReports/Report.css
changes to the edit page styling to match the current design patterns. The edit page has the same styling as the schedule survey page.
> Update styling on edit page

- client/src/components/InviteUser.js
- client/src/components/ManagerPoll.js
- client/src/components/PageTitle.js
- client/src/components/PollCalendar.js
- client/src/components/TableDisplay.js
- client/src/components/circleProgress.js
- client/src/pages/Dashboard/Dashboard.js
- client/src/pages/Login/Login.js
- client/src/pages/Marketing/DevTeam.js
- client/src/pages/Marketing/MarketingPage.js
- client/src/pages/MyTeam/myTeam.js
- client/src/pages/Navigation/Navigations.js
- client/src/pages/Reports/MemberReports/MemberResponseForm.js
- client/src/pages/Reports/MemberReports/ReportInput.js
- client/src/pages/Reports/MemberReports/ReportResults.js
- client/src/pages/Reports/ModifyReports/CreateReport.js
- client/src/pages/Reports/ModifyReports/CreateSentiment.js
- client/src/pages/Reports/Reports.js
- client/src/pages/Stats/ChartOptions.js
- client/src/pages/Stats/StatsDashboard.js
- client/src/pages/View/View.js
Removes all but 4 console warnings. Should make the logs a little bit easier to work with.
No bad effects on the app as far as I can tell.
> removes console errors

- client/src/pages/MyTeam/myTeam.css
- client/src/pages/MyTeam/myTeam.js
- client/src/pages/Reports/ModifyReports/CreateReport.js
- client/src/pages/View/View.js
made changes requested by users
> Updated tour and addd profile pics to my team

- client/src/pages/MyTeam/myTeam.js
- client/src/pages/Reports/ModifyReports/CreateReport.js
- client/src/pages/Reports/ModifyReports/Report.css
changing button on manager type within survey to make it longer and look more natural. old styling opened off to side. Styling for mobile completed as well
> Manager Button Styling

- client/src/pages/Marketing/MarketingPage.js
- client/src/pages/Marketing/marketingPage.css
- client/src/pages/Navigation/Navigations.js
- client/src/pages/Navigation/navigation.css
New marketing page draft 1; still need to edit the team page and a tiny bug fix with the vertical nav bar looking stragne for users 
- [x ] I have commented my code, particularly in hard-to-understand areas
> New marketing page 

- client/src/components/InviteUser.js
- client/src/pages/Navigation/Navigations.js
- client/src/pages/Reports/MemberReports/ReportInput.js
This pull request adds a NavLink to the survey button in mobile view. In the myTeams page. When you add email, the email does not clear, and is now cleared once you send it out
> Fixing mobile "add survey" button. Add email clear form

- client/src/components/PollCalendar.js
- client/src/pages/Reports/MemberReports/ReportResults.css
- client/src/pages/Reports/MemberReports/ReportResults.js
- client/src/pages/View/View.js
fixed bug where calendar would err out when selecting a day without reports. Now it just displays a "no reports for that day" message when a day without reports is selected. 
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
> Fixed calendar bug 

- client/src/App.js
- client/src/components/FeedBackForm/Confirm.js
- client/src/components/FeedBackForm/FeedBackForm.js
- client/src/components/FeedBackForm/FormQuestionaires.js
- client/src/components/FeedBackForm/FormUserDetails.js
- client/src/components/FeedBackForm/ThankYou.js
- client/src/components/FeedBackForm/withCardStyles.js
- client/src/pages/Reports/MemberReports/MemberResponseForm.js
Added basic feedback form to send an email.
Added a check so members can't respond to a form unless the scheduled time has been met.
> Responseform fix

- client/src/pages/Reports/MemberReports/MemberResponseForm.js
Bug fix where managers could not answer manager questions.
> fix bug where manager cannot answer questions

- client/src/components/ResponseCard.js
- client/src/pages/Reports/MemberReports/MemberResponseForm.js
- client/src/pages/Reports/MemberReports/ReportResults.js
- client/src/pages/Reports/ModifyReports/CreateReport.js
Managers now don't need to respond to manager questions if they opt out.
> Relieve manager stress

- client/package.json
- client/src/pages/MyTeam/myTeam.js
- client/src/pages/Onboarding/CreateTeam.js
- client/src/pages/Profile/profile.css
> Minor stle changes to edit form and redunant button removed

- client/src/pages/Marketing/DevTeam.js
- client/src/pages/Marketing/marketingPage.css
> styles team page

- client/src/components/ConfirmResponse.js
- client/src/components/ManagerFeedBackForUsers.js
- client/src/components/ManagerFeedbackForManagers.js
- client/src/components/ResponseCard.js
- client/src/pages/Reports/MemberReports/MemberResponseForm.js
- client/src/pages/Reports/MemberReports/ReportResults.js
Fix bug where surveys are not being displayed correctly
> Feedbackform fix

- client/src/pages/Reports/ModifyReports/CreateReport.js
change from 5 minutes increments to 1 minute for presentation
> change timepicker parameter
